### ISSUE TITLE
Diagrama de Casos de Uso del Sistema

### ISSUE THREAD

**Issue by see1004** [see1004/Tarea_02_Proceso_Iterativo_e_Incremental#1]
Identificar los actores, casos de uso y sus relaciones.

**Comment by dma1009** [comment]
Vale, os parece que nosotros sigamos con el diagrama?

**Comment by sml1010** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/126596622/28df1898-1c35-4d44-a3f6-c8467199d74f)

**Comment by dma1009** [comment]
así me gusta

**Comment by sml1010** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/126596622/db7f2c5c-18db-492b-bb2c-d66ae304afc8)

**Comment by jbs1009** [comment]
¡Qué eficiencia!

**Comment by jbs1009** [comment]
Una observación: En la parte baja del diagrama, donde dice que "Pedir datos paciente" extends "Pedir datos paciente", es un error. En realidad deberíais modificar el caso de uso de la izquierda por "Crear nueva ficha cliente". Además, tened en cuenta que la flecha del extends deberá apuntar hacia la derecha, pues ese es el caso obligatorio.

**Comment by dma1009** [comment]
Sí, es como dices, justo estábamos cambiándolo. Un segundo

**Comment by jbs1009** [comment]
Perfecto entonces!

**Comment by sml1010** [comment]
Buenas noticias: He corregido el fallo y he subido el diagrama en PDF en la parte de Code

**Comment by sml1010** [comment]
Hay una nueva modificación: El director no es un actor, porque no interactúa con el sistema. Os paso el nuevo diagrama:

**Comment by sml1010** [comment]
![Digrama Def](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/126596622/c0efd6e5-a900-4e68-af95-0ba3538b89f2)

**Comment by sml1010** [comment]
También he actualizado el PDF.

**Comment by dma1009** [comment]
Pues me parece a mí que no eh

**Comment by dma1009** [comment]
Cámbialo cuando puedas please

**Comment by sml1010** [comment]
Ya está el documento definitivo.

**Comment by see1004** [comment]
Cierro la tarea, si hay que cambiar algo la volvéis a abrir en un momento y listo.
