### ISSUE TITLE
Catálogo de requisitos funcionales.

### ISSUE THREAD

**Issue by see1004** [see1004/Tarea_02_Proceso_Iterativo_e_Incremental#2]
Se debe incluir el identificador único de cada requisito y una descripción formal de su funcionalidad. Razonar su importancia y prioridad. Seguir la siguiente tabla:

![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233780/8732c9c8-9b81-4ec2-8e43-1d736eac5413)

**Comment by dma1009** [comment]
Vale eso nosotros lo empezamos el otro día mientras estructurabais el trabajo

**Comment by sml1010** [comment]
Os paso un ejemplo del director:

**Comment by dma1009** [comment]
Creo que eso tiene que ir al issue de los actores no?

**Comment by sml1010** [comment]
Nada, fallo mío.

**Comment by see1004** [comment]
Sí, este apartado es para los requisitos que necesita nuestra aplicación. Tengo hechos yo 10 requisitos, los paso.

**Comment by see1004** [comment]
1. Datos de las clínicas.

**Comment by see1004** [comment]
2. Datos de los directores.

**Comment by see1004** [comment]
3. Datos de los empleados.

**Comment by see1004** [comment]
4. Datos de los pacientes.

**Comment by see1004** [comment]
5. Gestión de consultas.

**Comment by see1004** [comment]
6. Generación de citas.

**Comment by see1004** [comment]
7. Sistema de pago mensual.

**Comment by see1004** [comment]
8. Cálculo de facturas.

**Comment by see1004** [comment]
9. Historial de consultas.

**Comment by see1004** [comment]
10. Dar de alta un paciente.

**Comment by see1004** [comment]
Adjunto documento PDF por si hay que hacer cambios en alguno de los requisitos (incluido en el apartado de código).

**Comment by see1004** [comment]
Issue terminado a falta de revisar las prioridades de cada requisito, ajustad las prioridades si lo veis necesario.

**Comment by sml1010** [comment]
Yo lo veo bien.
