### ISSUE TITLE
Identificar los actores del sistema.

### ISSUE THREAD

**Issue by see1004** [see1004/Tarea_02_Proceso_Iterativo_e_Incremental#3]
Tipos de usuario y otros sistemas con los que se interactúa.

**Comment by dma1009** [comment]
**Vale,** esta es bastante fácil yo creo

**Comment by sml1010** [comment]
Creo que un tipo de usuario es el personal sanitario que interactúa con los pacientes del hospital.

**Comment by dma1009** [comment]
Lo hacemos nosotros

**Comment by dma1009** [comment]
Vale pues Sara, Jorge y yo
ajajajaj

**Comment by sml1010** [comment]
Me parece correcto.

**Comment by jbs1009** [comment]
Perfecto.

**Comment by dma1009** [comment]
Vale, creo que uno es director.

**Comment by jbs1009** [comment]
Estoy de acuerdo. Otro actor sería Médico, ¿cierto?

**Comment by dma1009** [comment]
Sí perfecto

**Comment by dma1009** [comment]
Vale, enfermero también

**Comment by sml1010** [comment]
Friendly reminder: El médico especialista y el médico es lo mismo, así que cuenta como un solo actor.

**Comment by dma1009** [comment]
Es vedad sí que se lo preguntamos el otro día

**Comment by jbs1009** [comment]
Vale, actores también serían Auxiliar y Administrativo

**Comment by sml1010** [comment]
Vale os paso las tablas que tenemos:

**Comment by sml1010** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/saram/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/saram/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/saram/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ES style='tab-interval:35.4pt;word-wrap:break-word'>




AC 1 | Director
-- | --
Descripción | Este actor podrá realizar las siguientes funcionalidades:    1)        Gestionar una única clínica a la vez
AC 2 | Médico
Descripción | Este actor   podrá realizar las   siguientes funcionalidades:    1.     Visualizar historial de consultas del paciente   (fecha, día y especialidad)   2.     Introducir datos de las pruebas necesarias que se   han realizado.
AC 3 | Enfermero
Descripción | Este actor   podrá realizar las   siguientes funcionalidades:    1.     Visualizar historial de consultas del paciente   (fecha, día y especialidad)
AC 4 | Auxiliar de enfermería
Descripción | Este actor   podrá realizar las   siguientes funcionalidades:    1.     Gestionar citas   sucesivas después de la primera   2.     Visualizar historial de consultas del paciente   (fecha, día y especialidad)
AC 5 | Administrativo
Descripción | Este actor   podrá realizar las   siguientes funcionalidades:    1)     Gestionar factura consulta   2)     Enviar ficheros de cargos domiciliados a entidad   bancaria colaboradora.    3)     Visualizar historial de consultas del paciente   (fecha, día y especialidad)   4)     Solicitar datos del paciente y crear ficha si no   está incluido en el sistema.
AC 6 | Paciente
Descripción | Este actor   podrá realizar las   siguientes funcionalidades:    1)        Solicitar cita presencialmente o por teléfono   2)        Decidir si quiere pagar la factura o que se acumule en su cuenta




</body>

</html>

**Comment by sml1010** [comment]
Coleguillas, acabo de adjuntar el PDF con la tabla de actores en la parte de Code.
