### ISSUE TITLE
Especificación formal de los casos de Uso

### ISSUE THREAD

**Issue by see1004** [see1004/Tarea_02_Proceso_Iterativo_e_Incremental#4]
Utilizando la tabla siguiente: 

![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233780/1250fa1c-1ee5-413f-b530-d0a449c56f89)

**Comment by dma1009** [comment]
eso no lo hemos empezado todavia

**Comment by jbs1009** [comment]
Nosotros nos encargamos de ello.

**Comment by see1004** [comment]
Yo estoy haciendo el de crear la ficha del paciente.

**Comment by sml1010** [comment]
Ya hemos acabado la tabla.
