### ISSUE TITLE
Realizar prototipo de pantallas

### ISSUE THREAD

**Issue by see1004** [see1004/Tarea_02_Proceso_Iterativo_e_Incremental#5]

**Comment by dma1009** [comment]
Vale tenemos que crear imágenes de como nos imaginamos la interfaz de pantalla en los pincipales casos

**Comment by jbs1009** [comment]
De acuerdo, ¿que os parece si usamos PowerPoint para ello?

**Comment by dma1009** [comment]
Sí, es lo que habíamos pensado ya

**Comment by jbs1009** [comment]
Perfecto entonces, mucho más cómodo creo yo

**Comment by dma1009** [comment]
A ver que os parece esta.

**Comment by dma1009** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233745/c55dadc9-c87f-4764-87fb-31a19f7968d0)

**Comment by see1004** [comment]
Está bonito, me gusta.

**Comment by jbs1009** [comment]
Me gusta, me gusta eh

**Comment by sml1010** [comment]
Ahora entiendo la idea.

**Comment by dma1009** [comment]
Ahí tengo otra

**Comment by dma1009** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233745/f1b0ad6f-073d-4972-9230-6a5be0400b9f)

**Comment by dma1009** [comment]
Y he cambiado un poco la otra

**Comment by dma1009** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233745/cf19b5d8-d28f-46bf-b51a-b5f2eb38620f)

**Comment by dma1009** [comment]
Estas interfaces son aquellas con las que va a contactar el paciente, por eso las hago con un tono más "amigable". Las que vayan a ser para ser usadas por los empleados pueden ser un poco más estilo "industrial"

**Comment by dma1009** [comment]
He hecho pequeños cambios.

**Comment by dma1009** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233745/087e4f4c-6d43-4dec-9550-8813d59edd3b)

**Comment by jbs1009** [comment]
Lo veo mejor así, genial.

**Comment by jbs1009** [comment]
¿Qué os parece este estilo para la interfaz de creación de nueva ficha técnica de paciente?

**Comment by jbs1009** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233780/550a3f39-88e2-4954-a73b-108930551668)

**Comment by dma1009** [comment]
Uffff muy chulo.
Me gusta más que los que he hecho yo aajajjaja.
Claro como es de los que utilizan los empleados es como más sobrio verdad?

**Comment by sml1010** [comment]
Me gusta mucho el formato. Es más adecuado para que lo utilicen los profesionales de la sanidad

**Comment by jbs1009** [comment]
Jajajaj, muchas gracias!
Esa era un poco la idea. Que las interfaces de los empleados de la clínica mantengan un estilo menos recargado.

**Comment by jbs1009** [comment]
Ahora os envío la diapositiva, por si queréis seguir el mismo formato para el resto de interfaces.

**Comment by dma1009** [comment]
Sí, sí, y así unificamos todos un poco el estilo de la interfaz. Yo dejaría las que he pasado yo ya para la interacción con el paciente y las que van a usar en sí los empleados vamos con ese estilo.

**Comment by jbs1009** [comment]
Me parece perfecto, adelante.

**Comment by dma1009** [comment]
Ahí va otro

**Comment by sml1010** [comment]
Yo tengo estas propuestas:

**Comment by dma1009** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233745/12c86506-1908-4120-ad7b-7667aade9c46)

**Comment by sml1010** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/126596622/ff14fbcf-e60d-4313-bd22-c3ee38d963b0)

**Comment by dma1009** [comment]
yo creo que mejor hacerlo nosotros desde cero como los que estamos pasando no?

**Comment by dma1009** [comment]
y ahí el último que me toca a mí

**Comment by dma1009** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233745/eaf4ca6b-a542-4577-a4fc-dee24a2ee0fa)

**Comment by dma1009** [comment]
Paso lo que tengo hasta ahora

**Comment by dma1009** [comment]
Tienes que hacer el que habías empezado ya y el de gestionar citas sucesivas

**Comment by sml1010** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/126596622/21e05074-c5d8-45ed-8d44-0d6c2b433558)

**Comment by sml1010** [comment]
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/126596622/8d10c730-5a98-45b0-9984-05912861078f)

**Comment by see1004** [comment]
Paso yo una forma posible de interfaz para el historial de las citas, con buscador.
![image](https://github.com/see1004/Tarea_02_Proceso_Iterativo_e_Incremental/assets/127233668/e9da1121-3082-4bab-873a-2fecb853ad35)
